"""empty message

Revision ID: 2a11669939bb
Revises: 180b1449ee5e
Create Date: 2018-12-26 17:21:21.512332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a11669939bb'
down_revision = '180b1449ee5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feature_client_priority'), 'feature', ['client_priority'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_client_priority'), table_name='feature')
    # ### end Alembic commands ###
